/* FITCOACH Atlas 3D — real interactive anatomy explorer */
const ANATOMY_URL='https://jixiangying.github.io/anatomy/';
const STYLE_ID='fitcoach-atlas-immersive-3d-style-v2';
function installStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.pro12-real3d-wrap{position:relative;width:100%;min-height:620px;border-radius:28px;overflow:hidden;background:#050806;border:1px solid rgba(255,255,255,.12);box-shadow:0 24px 60px rgba(0,0,0,.35)}
.pro12-real3d-wrap iframe{display:block;width:100%;height:620px;border:0;background:#050806}
.pro12-real3d-badge{position:absolute;z-index:3;top:14px;left:14px;padding:8px 12px;border:1px solid rgba(255,255,255,.12);border-radius:999px;background:rgba(7,10,8,.78);color:#fff;font-size:11px;font-weight:800;letter-spacing:.04em;backdrop-filter:blur(12px);pointer-events:none}
.pro12-real3d-note{display:flex;gap:8px;align-items:center;margin-top:10px;font-size:11px;color:rgba(255,255,255,.62)}
.pro12-real3d-dot{width:7px;height:7px;border-radius:50%;background:#72e3a0;box-shadow:0 0 12px rgba(114,227,160,.8);flex:none}
.pro12-real3d-open{position:absolute;z-index:4;right:14px;top:14px;border:1px solid rgba(255,255,255,.14);background:rgba(8,12,10,.84);color:#fff;border-radius:999px;padding:9px 13px;font-size:11px;font-weight:800;backdrop-filter:blur(12px);cursor:pointer}
@media(max-width:600px){.pro12-real3d-wrap,.pro12-real3d-wrap iframe{min-height:560px;height:560px}.pro12-real3d-open{top:52px;right:12px}}
`;document.head.appendChild(s)}
function enhanceAtlas(root=document){installStyle();const anatomy=root.querySelector('.pro12-anatomy');if(!anatomy||anatomy.dataset.immersive3d==='2')return;anatomy.dataset.immersive3d='2';const oldSvg=anatomy.querySelector('svg');const wrap=document.createElement('div');wrap.className='pro12-real3d-wrap';const badge=document.createElement('div');badge.className='pro12-real3d-badge';badge.textContent='● ATLAS 3D ANATÔMICO REAL';wrap.appendChild(badge);const open=document.createElement('button');open.className='pro12-real3d-open';open.type='button';open.textContent='Abrir em tela cheia';open.onclick=()=>window.open(ANATOMY_URL,'_blank','noopener,noreferrer');wrap.appendChild(open);const iframe=document.createElement('iframe');iframe.src=ANATOMY_URL;iframe.title='Atlas anatômico 3D interativo FITCOACH';iframe.loading='lazy';iframe.allow='fullscreen';iframe.setAttribute('allowfullscreen','');wrap.appendChild(iframe);oldSvg?.replaceWith(wrap);const caption=root.querySelector('.pro12-map-caption');if(caption&&!caption.querySelector('.pro12-real3d-note')){const n=document.createElement('div');n.className='pro12-real3d-note';n.innerHTML='<span class="pro12-real3d-dot"></span><span>3D anatômico real • gire • aproxime • selecione estruturas • explore músculos</span>';caption.appendChild(n)}}
new MutationObserver(()=>enhanceAtlas()).observe(document.documentElement,{childList:true,subtree:true});addEventListener('load',()=>enhanceAtlas());