(() => {
  if (window.__FITCOACH_AI_CHAT__) return
  window.__FITCOACH_AI_CHAT__ = true
  const key='fitcoach_ai_chat_v1'
  const state=JSON.parse(localStorage.getItem(key)||'{"role":"personal","student":"","messages":[]}')
  const save=()=>localStorage.setItem(key,JSON.stringify(state))
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))
  const style=document.createElement('style'); style.textContent=`
    /* IA FITCOACH — mobile safe zone: never overlap the bottom navigation or install CTA */
    #fc-ai-btn{position:fixed;right:16px;bottom:calc(190px + env(safe-area-inset-bottom));z-index:10050;width:58px;height:58px;min-width:58px;padding:0;border:1px solid rgba(114,227,160,.38);border-radius:18px;background:rgba(8,22,13,.97);color:#72e3a0;display:flex;align-items:center;justify-content:center;font-size:25px;font-weight:950;line-height:1;box-shadow:0 14px 38px rgba(0,0,0,.42),0 0 0 1px rgba(114,227,160,.06);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);cursor:pointer;transition:transform .18s ease,background .18s ease}
    #fc-ai-btn::after{content:'IA';position:absolute;right:-3px;bottom:-5px;padding:3px 6px;border-radius:8px;background:#72e3a0;color:#07100a;font-size:8px;font-weight:950;letter-spacing:.08em;box-shadow:0 4px 12px rgba(0,0,0,.3)}
    #fc-ai-btn:hover{transform:translateY(-2px);background:rgba(13,35,20,.98)} #fc-ai-btn:active{transform:scale(.96)}
    #fc-ai{position:fixed;right:16px;bottom:calc(258px + env(safe-area-inset-bottom));width:min(390px,calc(100vw - 32px));height:min(620px,calc(100vh - 300px));z-index:10051;background:#0d120f;color:#f5f7f5;border:1px solid #ffffff18;border-radius:22px;display:none;overflow:hidden;box-shadow:0 24px 70px #0009;font-family:Inter,system-ui,sans-serif}
    #fc-ai.open{display:flex;flex-direction:column}#fc-ai .hd{padding:14px 16px;border-bottom:1px solid #ffffff12;display:flex;justify-content:space-between;align-items:center}#fc-ai .sub{font-size:11px;opacity:.55}#fc-ai .x{background:none;border:0;color:#fff;font-size:22px;cursor:pointer}#fc-ai .ctx{padding:10px 12px;border-bottom:1px solid #ffffff12;display:flex;gap:8px}#fc-ai select,#fc-ai input{background:#141b17;color:#fff;border:1px solid #ffffff18;border-radius:10px;padding:9px;outline:none}#fc-ai select{width:105px}#fc-ai input{flex:1;min-width:0}#fc-ai .msgs{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px}#fc-ai .m{max-width:86%;padding:10px 12px;border-radius:14px;line-height:1.4;font-size:13px;white-space:pre-wrap}#fc-ai .user{align-self:flex-end;background:#72e3a0;color:#07100a}.bot{align-self:flex-start;background:#171e1a}.empty{opacity:.55;text-align:center;margin:auto;font-size:13px}#fc-ai form{display:flex;gap:8px;padding:12px;border-top:1px solid #ffffff12}#fc-ai textarea{flex:1;resize:none;background:#141b17;color:#fff;border:1px solid #ffffff18;border-radius:12px;padding:10px;min-height:42px;max-height:110px;outline:none}#fc-ai .send{border:0;border-radius:12px;background:#72e3a0;color:#07100a;font-weight:900;padding:0 14px;cursor:pointer}
    @media(max-width:520px){#fc-ai-btn{right:14px;bottom:calc(184px + env(safe-area-inset-bottom));width:54px;height:54px;min-width:54px;border-radius:17px}#fc-ai{right:12px;bottom:calc(246px + env(safe-area-inset-bottom));width:calc(100vw - 24px);height:min(560px,calc(100vh - 290px))}}
    @media(display-mode:standalone){#fc-ai-btn{bottom:calc(198px + env(safe-area-inset-bottom))}#fc-ai{bottom:calc(266px + env(safe-area-inset-bottom))}}
  `; document.head.appendChild(style)
  const wrap=document.createElement('div'); wrap.innerHTML=`<button id="fc-ai-btn" aria-label="Abrir IA FITCOACH" title="IA FITCOACH">✦</button><aside id="fc-ai" aria-label="Chat IA FITCOACH"><div class="hd"><div><strong>IA FITCOACH</strong><div class="sub">Dúvidas em tempo real</div></div><button class="x" id="fc-ai-close">×</button></div><div class="ctx"><select id="fc-role"><option value="personal">Personal</option><option value="aluno">Aluno</option></select><input id="fc-student" placeholder="Aluno (opcional)"></div><div class="msgs" id="fc-msgs"></div><form id="fc-form"><textarea id="fc-input" placeholder="Pergunte sobre treino, ficha ou acompanhamento..."></textarea><button class="send">Enviar</button></form></aside>`; document.body.appendChild(wrap)
  const panel=document.querySelector('#fc-ai'), msgs=document.querySelector('#fc-msgs'), role=document.querySelector('#fc-role'), student=document.querySelector('#fc-student')
  role.value=state.role; student.value=state.student
  const render=()=>{msgs.innerHTML=state.messages.length?state.messages.map(m=>`<div class="m ${m.r==='user'?'user':'bot'}">${esc(m.t)}</div>`).join(''):'<div class="empty">Pergunte qualquer coisa sobre treino, fichas e acompanhamento.</div>'; msgs.scrollTop=msgs.scrollHeight}
  render()
  document.querySelector('#fc-ai-btn').onclick=()=>panel.classList.add('open'); document.querySelector('#fc-ai-close').onclick=()=>panel.classList.remove('open')
  role.onchange=()=>{state.role=role.value;save()}; student.oninput=()=>{state.student=student.value;save()}
  document.querySelector('#fc-form').onsubmit=async e=>{e.preventDefault(); const input=document.querySelector('#fc-input'); const text=input.value.trim(); if(!text)return; state.messages.push({r:'user',t:text}); input.value=''; render(); save(); const loading={r:'bot',t:'Pensando...'}; state.messages.push(loading); render(); try{const res=await fetch('/api/ai-chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,role:state.role,student:state.student,history:state.messages.slice(-12,-1)})}); const data=await res.json(); loading.t=data.reply||data.error||'Não consegui responder agora.'}catch{loading.t='Não consegui conectar à IA agora. Verifique a configuração da IA no servidor.'} render();save()}
})()
